### ISSUE TITLE
为什么每次打开都提示我输入登陆密码呢？

### ISSUE THREAD

**Issue by ZhelinCheng** [cniPatch/NavicatPremium#11]
<img width="434" alt="WX20191231-204058@2x" src="https://user-images.githubusercontent.com/16441850/71622108-92a9fe80-2c0e-11ea-8c33-8645211673bb.png">

**Comment by cniPatch** [comment]
Path 过后的程序，证书校验不通过，系统会让你确认对新程序的授权。选 [始终允许] 就 OK 了。
