### ISSUE TITLE
12.1.12版本无法破解

### ISSUE THREAD

**Issue by atomshadows** [cniPatch/NavicatPremium#2]
安装的官方原版 Navicat 12.1.12，运行path.sh后发现SHA和脚本内置不一样，提示：您的文件版本不正确, 或已被修改, 请通过官方网站下载 Navicat Premium 12.1.12 简体中文版

修改脚本SHA变量后运行后  Navicat 闪退

**Comment by cniPatch** [comment]
SHA 验证码 shell 脚本里写错了，直接用 12.1.13吧。shell 里的验证更正了。
