### ISSUE TITLE
下载了12.1.24版本，破解的提示版本号不对

### ISSUE THREAD

**Issue by hongzhang7** [cniPatch/NavicatPremium#8]
下载了12.1.24版本，破解的提示版本号不对

**Comment by cniPatch** [comment]
`cat /Volumes/Navicat\ Premium/Navicat\ Premium.app/Contents/Info.plist | grep 12.1.`

加载镜像，在命令行下执行，上面代码，看看版本是不是12.1.24.

`<string>12.1.24</string>
	<string>12.1.2400</string>`

**Comment by cniPatch** [comment]
你试试最新的版本，重新 git clone 一下试试。
